-- Excel Easy Loader idempotent DDL - MariaDB 10.2+
-- 2026-08-14 이준혁

CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL PRIMARY KEY, JOB_NAME varchar(128) NOT NULL,
    HEADER_ROW int DEFAULT 1 NOT NULL, STRUCT_JSON longtext, MAPPING_JSON longtext,
    PRE_SQL_JSON longtext, POST_SQL_JSON longtext, ROW_SQL_JSON longtext,
    SAMPLE_FILE_NAME varchar(256), SAMPLE_FILE_ORG_NAME varchar(256), INSTRUCTIONS longtext,
    UPSERT_KEEP_EMPTY_YN char(1) DEFAULT 'N' NOT NULL,
    ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL,
    POST_SQL_ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL,
    MAX_UPLOAD_ROWS int DEFAULT 0 NOT NULL, REG_EMP_ID varchar(64),
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS UPLOAD_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS JOB_NAME varchar(128);
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS HEADER_ROW int DEFAULT 1;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS STRUCT_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS MAPPING_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS PRE_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS POST_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS ROW_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS SAMPLE_FILE_NAME varchar(256);
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS SAMPLE_FILE_ORG_NAME varchar(256);
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS INSTRUCTIONS longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS UPSERT_KEEP_EMPTY_YN char(1) DEFAULT 'N';
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N';
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS POST_SQL_ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N';
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS MAX_UPLOAD_ROWS int DEFAULT 0;
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS REG_EMP_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CONFIG ADD COLUMN IF NOT EXISTS REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS IDX_EXCEL_CONFIG_REG_DTTM ON ESO_EXCEL_UPLOAD_CONFIG (REG_DTTM);

CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_HISTORY (
    HIST_ID varchar(64) NOT NULL PRIMARY KEY, JOB_NAME varchar(128), FILE_NAME varchar(256),
    SUCCESS_CNT int DEFAULT 0 NOT NULL, FAIL_CNT int DEFAULT 0 NOT NULL,
    ATTEMPT_SUCCESS_CNT int DEFAULT 0 NOT NULL, ERROR_FILE varchar(256), UPLOAD_ID varchar(64),
    CONFIG_SNAPSHOT_HASH varchar(128), FAIL_TYPE_JSON longtext, CONFIG_STRUCT_JSON longtext,
    CONFIG_MAPPING_JSON longtext, CONFIG_PRE_SQL_JSON longtext, CONFIG_POST_SQL_JSON longtext,
    CONFIG_ROW_SQL_JSON longtext, RETRY_MODE varchar(32), RETRY_REASON_TYPES varchar(1000),
    ROLLED_BACK_YN char(1) DEFAULT 'N' NOT NULL,
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS HIST_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS JOB_NAME varchar(128);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS FILE_NAME varchar(256);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS SUCCESS_CNT int DEFAULT 0;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS FAIL_CNT int DEFAULT 0;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS ATTEMPT_SUCCESS_CNT int DEFAULT 0;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS ERROR_FILE varchar(256);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS UPLOAD_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_SNAPSHOT_HASH varchar(128);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS FAIL_TYPE_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_STRUCT_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_MAPPING_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_PRE_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_POST_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS CONFIG_ROW_SQL_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS RETRY_MODE varchar(32);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS RETRY_REASON_TYPES varchar(1000);
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS ROLLED_BACK_YN char(1) DEFAULT 'N';
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD COLUMN IF NOT EXISTS REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID ON ESO_EXCEL_UPLOAD_HISTORY (UPLOAD_ID);
CREATE INDEX IF NOT EXISTS IDX_EXCEL_HIST_REG_DTTM ON ESO_EXCEL_UPLOAD_HISTORY (REG_DTTM);

CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_CHANGE_HIST (
    CHANGE_ID varchar(64) NOT NULL PRIMARY KEY, HIST_ID varchar(64) NOT NULL, UPLOAD_ID varchar(64),
    JOB_ID varchar(64), TABLE_NAME varchar(128) NOT NULL, KEY_JSON longtext, BEFORE_JSON longtext,
    AFTER_JSON longtext, CHANGED_COLUMNS_JSON longtext, EXCEL_ROW_NO int, UPDATED_EMP_ID varchar(64),
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS CHANGE_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS HIST_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS UPLOAD_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS JOB_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS TABLE_NAME varchar(128);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS KEY_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS BEFORE_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS AFTER_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS CHANGED_COLUMNS_JSON longtext;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS EXCEL_ROW_NO int;
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS UPDATED_EMP_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST ADD COLUMN IF NOT EXISTS UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX IF NOT EXISTS IDX_EXCEL_CHANGE_HIST_ID ON ESO_EXCEL_UPLOAD_CHANGE_HIST (HIST_ID);
CREATE INDEX IF NOT EXISTS IDX_EXCEL_CHANGE_UPLOAD_ID ON ESO_EXCEL_UPLOAD_CHANGE_HIST (UPLOAD_ID);

CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_POOL_CONFIG (
    CONFIG_ID varchar(32) NOT NULL PRIMARY KEY, WORKER_COUNT int NOT NULL,
    QUEUE_CAPACITY int NOT NULL, UPDATED_EMP_ID varchar(64),
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG ADD COLUMN IF NOT EXISTS CONFIG_ID varchar(32);
ALTER TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG ADD COLUMN IF NOT EXISTS WORKER_COUNT int;
ALTER TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG ADD COLUMN IF NOT EXISTS QUEUE_CAPACITY int;
ALTER TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG ADD COLUMN IF NOT EXISTS UPDATED_EMP_ID varchar(64);
ALTER TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG ADD COLUMN IF NOT EXISTS UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS ESO_EXCEL_ALERT_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL PRIMARY KEY, ENABLED char(1) DEFAULT 'N' NOT NULL,
    WEBHOOK_URL_ENC longtext, FAIL_RATE_THRESHOLD int DEFAULT 0 NOT NULL,
    FAIL_COUNT_THRESHOLD int DEFAULT 0 NOT NULL,
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS UPLOAD_ID varchar(64);
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS ENABLED char(1) DEFAULT 'N';
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS WEBHOOK_URL_ENC longtext;
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS FAIL_RATE_THRESHOLD int DEFAULT 0;
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS FAIL_COUNT_THRESHOLD int DEFAULT 0;
ALTER TABLE ESO_EXCEL_ALERT_CONFIG ADD COLUMN IF NOT EXISTS UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP;

CREATE TEMPORARY TABLE IF NOT EXISTS TMP_EXCEL_UPLOAD_KEYS (
    ALIAS varchar(64), TABLE_NAME varchar(128), PK_COL varchar(128), PK_VAL varchar(128)
) ENGINE=InnoDB;
