-- Excel Easy Loader idempotent DDL - Tibero 6+
-- 2026-08-14 이준혁
-- 현재 접속 사용자의 USER_* 메타데이터를 기준으로 반복 실행할 수 있다.

DECLARE
    V_COUNT NUMBER;
    PROCEDURE ENSURE_TABLE(P_NAME VARCHAR2, P_DDL VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = UPPER(P_NAME);
        IF V_COUNT = 0 THEN EXECUTE IMMEDIATE P_DDL; END IF;
    END;
    PROCEDURE ENSURE_COLUMN(P_TABLE VARCHAR2, P_COLUMN VARCHAR2, P_DEFINITION VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS
         WHERE TABLE_NAME = UPPER(P_TABLE) AND COLUMN_NAME = UPPER(P_COLUMN);
        IF V_COUNT = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || P_TABLE || ' ADD (' || P_COLUMN || ' ' || P_DEFINITION || ')';
        END IF;
    END;
    PROCEDURE ENSURE_INDEX(P_NAME VARCHAR2, P_TABLE VARCHAR2, P_COLUMNS VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = UPPER(P_NAME);
        IF V_COUNT = 0 THEN
            EXECUTE IMMEDIATE 'CREATE INDEX ' || P_NAME || ' ON ' || P_TABLE || ' (' || P_COLUMNS || ')';
        END IF;
    END;
BEGIN
    ENSURE_TABLE('ESO_EXCEL_UPLOAD_CONFIG', q'~CREATE TABLE ESO_EXCEL_UPLOAD_CONFIG (
        UPLOAD_ID VARCHAR2(64) NOT NULL, JOB_NAME VARCHAR2(128) NOT NULL,
        HEADER_ROW NUMBER(10) DEFAULT 1 NOT NULL, STRUCT_JSON CLOB, MAPPING_JSON CLOB,
        PRE_SQL_JSON CLOB, POST_SQL_JSON CLOB, ROW_SQL_JSON CLOB,
        SAMPLE_FILE_NAME VARCHAR2(256), SAMPLE_FILE_ORG_NAME VARCHAR2(256), INSTRUCTIONS CLOB,
        UPSERT_KEEP_EMPTY_YN CHAR(1) DEFAULT 'N' NOT NULL,
        ROLLBACK_ON_FAIL_YN CHAR(1) DEFAULT 'N' NOT NULL,
        POST_SQL_ROLLBACK_ON_FAIL_YN CHAR(1) DEFAULT 'N' NOT NULL,
        MAX_UPLOAD_ROWS NUMBER(10) DEFAULT 0 NOT NULL, REG_EMP_ID VARCHAR2(64),
        REG_DTTM DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_ESO_EXCEL_UPLOAD_CONFIG PRIMARY KEY (UPLOAD_ID))~');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','UPLOAD_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','JOB_NAME','VARCHAR2(128)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','HEADER_ROW','NUMBER(10) DEFAULT 1');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','STRUCT_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','MAPPING_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','PRE_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','POST_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','ROW_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','SAMPLE_FILE_NAME','VARCHAR2(256)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','SAMPLE_FILE_ORG_NAME','VARCHAR2(256)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','INSTRUCTIONS','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','UPSERT_KEEP_EMPTY_YN','CHAR(1) DEFAULT ''N''');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','ROLLBACK_ON_FAIL_YN','CHAR(1) DEFAULT ''N''');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','POST_SQL_ROLLBACK_ON_FAIL_YN','CHAR(1) DEFAULT ''N''');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','MAX_UPLOAD_ROWS','NUMBER(10) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','REG_EMP_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','REG_DTTM','DATE DEFAULT SYSDATE');
    ENSURE_INDEX('IDX_EXCEL_CONFIG_REG_DTTM','ESO_EXCEL_UPLOAD_CONFIG','REG_DTTM');

    ENSURE_TABLE('ESO_EXCEL_UPLOAD_HISTORY', q'~CREATE TABLE ESO_EXCEL_UPLOAD_HISTORY (
        HIST_ID VARCHAR2(64) NOT NULL, JOB_NAME VARCHAR2(128), FILE_NAME VARCHAR2(256),
        SUCCESS_CNT NUMBER(10) DEFAULT 0 NOT NULL, FAIL_CNT NUMBER(10) DEFAULT 0 NOT NULL,
        ATTEMPT_SUCCESS_CNT NUMBER(10) DEFAULT 0 NOT NULL, ERROR_FILE VARCHAR2(256), UPLOAD_ID VARCHAR2(64),
        CONFIG_SNAPSHOT_HASH VARCHAR2(128), FAIL_TYPE_JSON CLOB, CONFIG_STRUCT_JSON CLOB,
        CONFIG_MAPPING_JSON CLOB, CONFIG_PRE_SQL_JSON CLOB, CONFIG_POST_SQL_JSON CLOB,
        CONFIG_ROW_SQL_JSON CLOB, RETRY_MODE VARCHAR2(32), RETRY_REASON_TYPES VARCHAR2(1000),
        ROLLED_BACK_YN CHAR(1) DEFAULT 'N' NOT NULL, REG_DTTM DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_ESO_EXCEL_UPLOAD_HISTORY PRIMARY KEY (HIST_ID))~');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','HIST_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','JOB_NAME','VARCHAR2(128)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FILE_NAME','VARCHAR2(256)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','SUCCESS_CNT','NUMBER(10) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FAIL_CNT','NUMBER(10) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ATTEMPT_SUCCESS_CNT','NUMBER(10) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ERROR_FILE','VARCHAR2(256)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','UPLOAD_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_SNAPSHOT_HASH','VARCHAR2(128)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FAIL_TYPE_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_STRUCT_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_MAPPING_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_PRE_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_POST_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_ROW_SQL_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','RETRY_MODE','VARCHAR2(32)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','RETRY_REASON_TYPES','VARCHAR2(1000)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ROLLED_BACK_YN','CHAR(1) DEFAULT ''N''');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','REG_DTTM','DATE DEFAULT SYSDATE');
    ENSURE_INDEX('IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID','ESO_EXCEL_UPLOAD_HISTORY','UPLOAD_ID');
    ENSURE_INDEX('IDX_EXCEL_HIST_REG_DTTM','ESO_EXCEL_UPLOAD_HISTORY','REG_DTTM');

    ENSURE_TABLE('ESO_EXCEL_UPLOAD_CHANGE_HIST', q'~CREATE TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST (
        CHANGE_ID VARCHAR2(64) NOT NULL, HIST_ID VARCHAR2(64) NOT NULL, UPLOAD_ID VARCHAR2(64),
        JOB_ID VARCHAR2(64), TABLE_NAME VARCHAR2(128) NOT NULL, KEY_JSON CLOB, BEFORE_JSON CLOB,
        AFTER_JSON CLOB, CHANGED_COLUMNS_JSON CLOB, EXCEL_ROW_NO NUMBER(10), UPDATED_EMP_ID VARCHAR2(64),
        UPDATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_EXCEL_CHANGE_HIST PRIMARY KEY (CHANGE_ID))~');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','CHANGE_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','HIST_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPLOAD_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','JOB_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','TABLE_NAME','VARCHAR2(128)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','KEY_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','BEFORE_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','AFTER_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','CHANGED_COLUMNS_JSON','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','EXCEL_ROW_NO','NUMBER(10)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPDATED_EMP_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPDATED_DTTM','TIMESTAMP DEFAULT CURRENT_TIMESTAMP');
    ENSURE_INDEX('IDX_EXCEL_CHANGE_HIST_ID','ESO_EXCEL_UPLOAD_CHANGE_HIST','HIST_ID');
    ENSURE_INDEX('IDX_EXCEL_CHANGE_UPLOAD_ID','ESO_EXCEL_UPLOAD_CHANGE_HIST','UPLOAD_ID');

    ENSURE_TABLE('ESO_EXCEL_UPLOAD_POOL_CONFIG', q'~CREATE TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG (
        CONFIG_ID VARCHAR2(32) NOT NULL, WORKER_COUNT NUMBER(5) NOT NULL, QUEUE_CAPACITY NUMBER(5) NOT NULL,
        UPDATED_EMP_ID VARCHAR2(64), UPDATED_DTTM DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_EXCEL_POOL_CONFIG PRIMARY KEY (CONFIG_ID))~');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','CONFIG_ID','VARCHAR2(32)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','WORKER_COUNT','NUMBER(5)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','QUEUE_CAPACITY','NUMBER(5)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','UPDATED_EMP_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','UPDATED_DTTM','DATE DEFAULT SYSDATE');

    ENSURE_TABLE('ESO_EXCEL_ALERT_CONFIG', q'~CREATE TABLE ESO_EXCEL_ALERT_CONFIG (
        UPLOAD_ID VARCHAR2(64) NOT NULL, ENABLED CHAR(1) DEFAULT 'N' NOT NULL, WEBHOOK_URL_ENC CLOB,
        FAIL_RATE_THRESHOLD NUMBER(5) DEFAULT 0 NOT NULL, FAIL_COUNT_THRESHOLD NUMBER(10) DEFAULT 0 NOT NULL,
        UPDATED_DTTM DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_EXCEL_ALERT_CONFIG PRIMARY KEY (UPLOAD_ID))~');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','UPLOAD_ID','VARCHAR2(64)');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','ENABLED','CHAR(1) DEFAULT ''N''');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','WEBHOOK_URL_ENC','CLOB');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','FAIL_RATE_THRESHOLD','NUMBER(5) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','FAIL_COUNT_THRESHOLD','NUMBER(10) DEFAULT 0');
    ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','UPDATED_DTTM','DATE DEFAULT SYSDATE');

    ENSURE_TABLE('TMP_EXCEL_UPLOAD_KEYS', q'~CREATE GLOBAL TEMPORARY TABLE TMP_EXCEL_UPLOAD_KEYS (
        ALIAS VARCHAR2(64), TABLE_NAME VARCHAR2(128), PK_COL VARCHAR2(128), PK_VAL VARCHAR2(128)
    ) ON COMMIT PRESERVE ROWS~');
    ENSURE_COLUMN('TMP_EXCEL_UPLOAD_KEYS','ALIAS','VARCHAR2(64)');
    ENSURE_COLUMN('TMP_EXCEL_UPLOAD_KEYS','TABLE_NAME','VARCHAR2(128)');
    ENSURE_COLUMN('TMP_EXCEL_UPLOAD_KEYS','PK_COL','VARCHAR2(128)');
    ENSURE_COLUMN('TMP_EXCEL_UPLOAD_KEYS','PK_VAL','VARCHAR2(128)');
END;
/
