-- Excel Easy Loader idempotent DDL - MySQL 5.7 / 8.0+
-- 2026-08-14 이준혁
-- 컬럼 단위 IF NOT EXISTS 호환성을 위해 실행 후 제거되는 보조 프로시저를 사용한다.

CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL PRIMARY KEY, JOB_NAME varchar(128) NOT NULL,
    HEADER_ROW int DEFAULT 1 NOT NULL, STRUCT_JSON longtext, MAPPING_JSON longtext,
    PRE_SQL_JSON longtext, POST_SQL_JSON longtext, ROW_SQL_JSON longtext,
    SAMPLE_FILE_NAME varchar(256), SAMPLE_FILE_ORG_NAME varchar(256), INSTRUCTIONS longtext,
    UPSERT_KEEP_EMPTY_YN char(1) DEFAULT 'N' NOT NULL,
    ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL,
    POST_SQL_ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL,
    MAX_UPLOAD_ROWS int DEFAULT 0 NOT NULL, REG_EMP_ID varchar(64),
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_HISTORY (
    HIST_ID varchar(64) NOT NULL PRIMARY KEY, JOB_NAME varchar(128), FILE_NAME varchar(256),
    SUCCESS_CNT int DEFAULT 0 NOT NULL, FAIL_CNT int DEFAULT 0 NOT NULL,
    ATTEMPT_SUCCESS_CNT int DEFAULT 0 NOT NULL, ERROR_FILE varchar(256), UPLOAD_ID varchar(64),
    CONFIG_SNAPSHOT_HASH varchar(128), FAIL_TYPE_JSON longtext, CONFIG_STRUCT_JSON longtext,
    CONFIG_MAPPING_JSON longtext, CONFIG_PRE_SQL_JSON longtext, CONFIG_POST_SQL_JSON longtext,
    CONFIG_ROW_SQL_JSON longtext, RETRY_MODE varchar(32), RETRY_REASON_TYPES varchar(1000),
    ROLLED_BACK_YN char(1) DEFAULT 'N' NOT NULL,
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_CHANGE_HIST (
    CHANGE_ID varchar(64) NOT NULL PRIMARY KEY, HIST_ID varchar(64) NOT NULL, UPLOAD_ID varchar(64),
    JOB_ID varchar(64), TABLE_NAME varchar(128) NOT NULL, KEY_JSON longtext, BEFORE_JSON longtext,
    AFTER_JSON longtext, CHANGED_COLUMNS_JSON longtext, EXCEL_ROW_NO int, UPDATED_EMP_ID varchar(64),
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ESO_EXCEL_UPLOAD_POOL_CONFIG (
    CONFIG_ID varchar(32) NOT NULL PRIMARY KEY, WORKER_COUNT int NOT NULL,
    QUEUE_CAPACITY int NOT NULL, UPDATED_EMP_ID varchar(64),
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ESO_EXCEL_ALERT_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL PRIMARY KEY, ENABLED char(1) DEFAULT 'N' NOT NULL,
    WEBHOOK_URL_ENC longtext, FAIL_RATE_THRESHOLD int DEFAULT 0 NOT NULL,
    FAIL_COUNT_THRESHOLD int DEFAULT 0 NOT NULL,
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER $$
DROP PROCEDURE IF EXISTS EXCEL_ENSURE_COLUMN$$
CREATE PROCEDURE EXCEL_ENSURE_COLUMN(IN P_TABLE varchar(64), IN P_COLUMN varchar(64), IN P_DEFINITION text)
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = DATABASE() AND table_name = P_TABLE AND column_name = P_COLUMN
    ) THEN
        SET @DDL = CONCAT('ALTER TABLE `', P_TABLE, '` ADD COLUMN `', P_COLUMN, '` ', P_DEFINITION);
        PREPARE EXCEL_STMT FROM @DDL;
        EXECUTE EXCEL_STMT;
        DEALLOCATE PREPARE EXCEL_STMT;
    END IF;
END$$
DROP PROCEDURE IF EXISTS EXCEL_ENSURE_INDEX$$
CREATE PROCEDURE EXCEL_ENSURE_INDEX(IN P_TABLE varchar(64), IN P_INDEX varchar(64), IN P_COLUMNS varchar(255))
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.statistics
         WHERE table_schema = DATABASE() AND table_name = P_TABLE AND index_name = P_INDEX
    ) THEN
        SET @DDL = CONCAT('CREATE INDEX `', P_INDEX, '` ON `', P_TABLE, '` (', P_COLUMNS, ')');
        PREPARE EXCEL_STMT FROM @DDL;
        EXECUTE EXCEL_STMT;
        DEALLOCATE PREPARE EXCEL_STMT;
    END IF;
END$$
DELIMITER ;

CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','UPLOAD_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','JOB_NAME','varchar(128)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','HEADER_ROW','int DEFAULT 1');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','STRUCT_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','MAPPING_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','PRE_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','POST_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','ROW_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','SAMPLE_FILE_NAME','varchar(256)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','SAMPLE_FILE_ORG_NAME','varchar(256)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','INSTRUCTIONS','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','UPSERT_KEEP_EMPTY_YN','char(1) DEFAULT ''N''');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','ROLLBACK_ON_FAIL_YN','char(1) DEFAULT ''N''');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','POST_SQL_ROLLBACK_ON_FAIL_YN','char(1) DEFAULT ''N''');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','MAX_UPLOAD_ROWS','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','REG_EMP_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CONFIG','REG_DTTM','datetime DEFAULT CURRENT_TIMESTAMP');

CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','HIST_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','JOB_NAME','varchar(128)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FILE_NAME','varchar(256)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','SUCCESS_CNT','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FAIL_CNT','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ATTEMPT_SUCCESS_CNT','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ERROR_FILE','varchar(256)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','UPLOAD_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_SNAPSHOT_HASH','varchar(128)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','FAIL_TYPE_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_STRUCT_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_MAPPING_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_PRE_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_POST_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','CONFIG_ROW_SQL_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','RETRY_MODE','varchar(32)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','RETRY_REASON_TYPES','varchar(1000)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','ROLLED_BACK_YN','char(1) DEFAULT ''N''');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_HISTORY','REG_DTTM','datetime DEFAULT CURRENT_TIMESTAMP');

CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','CHANGE_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','HIST_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPLOAD_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','JOB_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','TABLE_NAME','varchar(128)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','KEY_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','BEFORE_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','AFTER_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','CHANGED_COLUMNS_JSON','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','EXCEL_ROW_NO','int');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPDATED_EMP_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_CHANGE_HIST','UPDATED_DTTM','datetime DEFAULT CURRENT_TIMESTAMP');

CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','CONFIG_ID','varchar(32)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','WORKER_COUNT','int');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','QUEUE_CAPACITY','int');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','UPDATED_EMP_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_UPLOAD_POOL_CONFIG','UPDATED_DTTM','datetime DEFAULT CURRENT_TIMESTAMP');

CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','UPLOAD_ID','varchar(64)');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','ENABLED','char(1) DEFAULT ''N''');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','WEBHOOK_URL_ENC','longtext');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','FAIL_RATE_THRESHOLD','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','FAIL_COUNT_THRESHOLD','int DEFAULT 0');
CALL EXCEL_ENSURE_COLUMN('ESO_EXCEL_ALERT_CONFIG','UPDATED_DTTM','datetime DEFAULT CURRENT_TIMESTAMP');

CALL EXCEL_ENSURE_INDEX('ESO_EXCEL_UPLOAD_CONFIG','IDX_EXCEL_CONFIG_REG_DTTM','REG_DTTM');
CALL EXCEL_ENSURE_INDEX('ESO_EXCEL_UPLOAD_HISTORY','IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID','UPLOAD_ID');
CALL EXCEL_ENSURE_INDEX('ESO_EXCEL_UPLOAD_HISTORY','IDX_EXCEL_HIST_REG_DTTM','REG_DTTM');
CALL EXCEL_ENSURE_INDEX('ESO_EXCEL_UPLOAD_CHANGE_HIST','IDX_EXCEL_CHANGE_HIST_ID','HIST_ID');
CALL EXCEL_ENSURE_INDEX('ESO_EXCEL_UPLOAD_CHANGE_HIST','IDX_EXCEL_CHANGE_UPLOAD_ID','UPLOAD_ID');

DROP PROCEDURE EXCEL_ENSURE_COLUMN;
DROP PROCEDURE EXCEL_ENSURE_INDEX;

CREATE TEMPORARY TABLE IF NOT EXISTS TMP_EXCEL_UPLOAD_KEYS (
    ALIAS varchar(64), TABLE_NAME varchar(128), PK_COL varchar(128), PK_VAL varchar(128)
) ENGINE=InnoDB;
