-- 2026-04-26: ESO_EXCEL_UPLOAD_HISTORY에 UPLOAD_ID 컬럼을 추가하고 기존 조회 경로를 안정화한다.
ALTER TABLE ESO_EXCEL_UPLOAD_HISTORY ADD (UPLOAD_ID VARCHAR2(64));

-- 필요 시 인덱스를 추가한다.
-- CREATE INDEX IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID ON ESO_EXCEL_UPLOAD_HISTORY (UPLOAD_ID);

-- 기존 이력은 업로드 소스 로그가 남아 있는 경우에만 백필한다.
-- 예시:
-- UPDATE ESO_EXCEL_UPLOAD_HISTORY
--    SET UPLOAD_ID = :upload_id
--  WHERE HIST_ID = :hist_id;
