-- Excel Easy Loader 전체 초기 DDL - MySQL 8.0+
-- 2026-08-12 이준혁

CREATE TABLE ESO_EXCEL_UPLOAD_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL, JOB_NAME varchar(128) NOT NULL, HEADER_ROW int DEFAULT 1 NOT NULL,
    STRUCT_JSON longtext, MAPPING_JSON longtext, PRE_SQL_JSON longtext, POST_SQL_JSON longtext, ROW_SQL_JSON longtext,
    SAMPLE_FILE_NAME varchar(256), SAMPLE_FILE_ORG_NAME varchar(256), INSTRUCTIONS longtext,
    UPSERT_KEEP_EMPTY_YN char(1) DEFAULT 'N' NOT NULL CHECK (UPSERT_KEEP_EMPTY_YN IN ('Y','N')),
    ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL CHECK (ROLLBACK_ON_FAIL_YN IN ('Y','N')),
    POST_SQL_ROLLBACK_ON_FAIL_YN char(1) DEFAULT 'N' NOT NULL CHECK (POST_SQL_ROLLBACK_ON_FAIL_YN IN ('Y','N')),
    MAX_UPLOAD_ROWS int DEFAULT 0 NOT NULL, REG_EMP_ID varchar(64),
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (UPLOAD_ID), KEY IDX_EXCEL_CONFIG_REG_DTTM (REG_DTTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ESO_EXCEL_UPLOAD_HISTORY (
    HIST_ID varchar(64) NOT NULL, JOB_NAME varchar(128), FILE_NAME varchar(256),
    SUCCESS_CNT int DEFAULT 0 NOT NULL, FAIL_CNT int DEFAULT 0 NOT NULL, ATTEMPT_SUCCESS_CNT int DEFAULT 0 NOT NULL,
    ERROR_FILE varchar(256), UPLOAD_ID varchar(64), CONFIG_SNAPSHOT_HASH varchar(128), FAIL_TYPE_JSON longtext,
    CONFIG_STRUCT_JSON longtext, CONFIG_MAPPING_JSON longtext, CONFIG_PRE_SQL_JSON longtext,
    CONFIG_POST_SQL_JSON longtext, CONFIG_ROW_SQL_JSON longtext, RETRY_MODE varchar(32),
    RETRY_REASON_TYPES varchar(1000), ROLLED_BACK_YN char(1) DEFAULT 'N' NOT NULL CHECK (ROLLED_BACK_YN IN ('Y','N')),
    REG_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (HIST_ID), KEY IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID (UPLOAD_ID),
    KEY IDX_EXCEL_HIST_REG_DTTM (REG_DTTM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST (
    CHANGE_ID varchar(64) NOT NULL, HIST_ID varchar(64) NOT NULL, UPLOAD_ID varchar(64), JOB_ID varchar(64),
    TABLE_NAME varchar(128) NOT NULL, KEY_JSON longtext, BEFORE_JSON longtext, AFTER_JSON longtext,
    CHANGED_COLUMNS_JSON longtext, EXCEL_ROW_NO int, UPDATED_EMP_ID varchar(64),
    UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CHANGE_ID), KEY IDX_EXCEL_CHANGE_HIST_ID (HIST_ID), KEY IDX_EXCEL_CHANGE_UPLOAD_ID (UPLOAD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG (
    CONFIG_ID varchar(32) NOT NULL, WORKER_COUNT int NOT NULL CHECK (WORKER_COUNT BETWEEN 1 AND 32),
    QUEUE_CAPACITY int NOT NULL CHECK (QUEUE_CAPACITY BETWEEN 1 AND 100),
    UPDATED_EMP_ID varchar(64), UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ESO_EXCEL_ALERT_CONFIG (
    UPLOAD_ID varchar(64) NOT NULL, ENABLED char(1) DEFAULT 'N' NOT NULL CHECK (ENABLED IN ('Y','N')),
    WEBHOOK_URL_ENC longtext, FAIL_RATE_THRESHOLD int DEFAULT 0 NOT NULL,
    FAIL_COUNT_THRESHOLD int DEFAULT 0 NOT NULL, UPDATED_DTTM datetime DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (UPLOAD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TEMPORARY 테이블은 연결별 객체이므로 애플리케이션이 각 연결에서 자동 생성한다.
-- 수동 검증이 필요할 때만 같은 연결에서 아래 문장을 실행한다.
CREATE TEMPORARY TABLE TMP_EXCEL_UPLOAD_KEYS (
    ALIAS varchar(64), TABLE_NAME varchar(128), PK_COL varchar(128), PK_VAL varchar(128)
) ENGINE=InnoDB;
