-- Excel Easy Loader 전체 초기 DDL - Tibero
-- 2026-08-12 이준혁

CREATE TABLE ESO_EXCEL_UPLOAD_CONFIG (
    UPLOAD_ID VARCHAR2(64) NOT NULL, JOB_NAME VARCHAR2(128) NOT NULL,
    HEADER_ROW NUMBER(10) DEFAULT 1 NOT NULL, STRUCT_JSON CLOB, MAPPING_JSON CLOB,
    PRE_SQL_JSON CLOB, POST_SQL_JSON CLOB, ROW_SQL_JSON CLOB,
    SAMPLE_FILE_NAME VARCHAR2(256), SAMPLE_FILE_ORG_NAME VARCHAR2(256), INSTRUCTIONS CLOB,
    UPSERT_KEEP_EMPTY_YN CHAR(1) DEFAULT 'N' NOT NULL,
    ROLLBACK_ON_FAIL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    POST_SQL_ROLLBACK_ON_FAIL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    MAX_UPLOAD_ROWS NUMBER(10) DEFAULT 0 NOT NULL, REG_EMP_ID VARCHAR2(64),
    REG_DTTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ESO_EXCEL_UPLOAD_CONFIG PRIMARY KEY (UPLOAD_ID),
    CONSTRAINT CK_EXCEL_CFG_KEEP CHECK (UPSERT_KEEP_EMPTY_YN IN ('Y','N')),
    CONSTRAINT CK_EXCEL_CFG_ROLL CHECK (ROLLBACK_ON_FAIL_YN IN ('Y','N')),
    CONSTRAINT CK_EXCEL_CFG_POST_ROLL CHECK (POST_SQL_ROLLBACK_ON_FAIL_YN IN ('Y','N'))
);
CREATE INDEX IDX_EXCEL_CONFIG_REG_DTTM ON ESO_EXCEL_UPLOAD_CONFIG (REG_DTTM);

CREATE TABLE ESO_EXCEL_UPLOAD_HISTORY (
    HIST_ID VARCHAR2(64) NOT NULL, JOB_NAME VARCHAR2(128), FILE_NAME VARCHAR2(256),
    SUCCESS_CNT NUMBER(10) DEFAULT 0 NOT NULL, FAIL_CNT NUMBER(10) DEFAULT 0 NOT NULL,
    ATTEMPT_SUCCESS_CNT NUMBER(10) DEFAULT 0 NOT NULL, ERROR_FILE VARCHAR2(256), UPLOAD_ID VARCHAR2(64),
    CONFIG_SNAPSHOT_HASH VARCHAR2(128), FAIL_TYPE_JSON CLOB, CONFIG_STRUCT_JSON CLOB,
    CONFIG_MAPPING_JSON CLOB, CONFIG_PRE_SQL_JSON CLOB, CONFIG_POST_SQL_JSON CLOB,
    CONFIG_ROW_SQL_JSON CLOB, RETRY_MODE VARCHAR2(32), RETRY_REASON_TYPES VARCHAR2(1000),
    ROLLED_BACK_YN CHAR(1) DEFAULT 'N' NOT NULL, REG_DTTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ESO_EXCEL_UPLOAD_HISTORY PRIMARY KEY (HIST_ID),
    CONSTRAINT CK_EXCEL_HIST_ROLL CHECK (ROLLED_BACK_YN IN ('Y','N'))
);
CREATE INDEX IDX_ESO_EXCEL_UPLOAD_HISTORY_UPLOAD_ID ON ESO_EXCEL_UPLOAD_HISTORY (UPLOAD_ID);
CREATE INDEX IDX_EXCEL_HIST_REG_DTTM ON ESO_EXCEL_UPLOAD_HISTORY (REG_DTTM);

CREATE TABLE ESO_EXCEL_UPLOAD_CHANGE_HIST (
    CHANGE_ID VARCHAR2(64) NOT NULL, HIST_ID VARCHAR2(64) NOT NULL, UPLOAD_ID VARCHAR2(64), JOB_ID VARCHAR2(64),
    TABLE_NAME VARCHAR2(128) NOT NULL, KEY_JSON CLOB, BEFORE_JSON CLOB, AFTER_JSON CLOB,
    CHANGED_COLUMNS_JSON CLOB, EXCEL_ROW_NO NUMBER(10), UPDATED_EMP_ID VARCHAR2(64),
    UPDATED_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_EXCEL_CHANGE_HIST PRIMARY KEY (CHANGE_ID)
);
CREATE INDEX IDX_EXCEL_CHANGE_HIST_ID ON ESO_EXCEL_UPLOAD_CHANGE_HIST (HIST_ID);
CREATE INDEX IDX_EXCEL_CHANGE_UPLOAD_ID ON ESO_EXCEL_UPLOAD_CHANGE_HIST (UPLOAD_ID);

CREATE TABLE ESO_EXCEL_UPLOAD_POOL_CONFIG (
    CONFIG_ID VARCHAR2(32) NOT NULL, WORKER_COUNT NUMBER(5) NOT NULL, QUEUE_CAPACITY NUMBER(5) NOT NULL,
    UPDATED_EMP_ID VARCHAR2(64), UPDATED_DTTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EXCEL_POOL_CONFIG PRIMARY KEY (CONFIG_ID),
    CONSTRAINT CK_EXCEL_POOL_WORKER CHECK (WORKER_COUNT BETWEEN 1 AND 32),
    CONSTRAINT CK_EXCEL_POOL_QUEUE CHECK (QUEUE_CAPACITY BETWEEN 1 AND 100)
);

CREATE TABLE ESO_EXCEL_ALERT_CONFIG (
    UPLOAD_ID VARCHAR2(64) NOT NULL, ENABLED CHAR(1) DEFAULT 'N' NOT NULL, WEBHOOK_URL_ENC CLOB,
    FAIL_RATE_THRESHOLD NUMBER(5) DEFAULT 0 NOT NULL, FAIL_COUNT_THRESHOLD NUMBER(10) DEFAULT 0 NOT NULL,
    UPDATED_DTTM DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EXCEL_ALERT_CONFIG PRIMARY KEY (UPLOAD_ID),
    CONSTRAINT CK_EXCEL_ALERT_ENABLED CHECK (ENABLED IN ('Y','N'))
);

CREATE GLOBAL TEMPORARY TABLE TMP_EXCEL_UPLOAD_KEYS (
    ALIAS VARCHAR2(64), TABLE_NAME VARCHAR2(128), PK_COL VARCHAR2(128), PK_VAL VARCHAR2(128)
) ON COMMIT PRESERVE ROWS;
